### ISSUE TITLE
Unnecessary use of JQuery

### ISSUE THREAD

**Issue by TheLukaszNs** [rohancl/BassaExtension#5]
The extension is using **JQuery** which is an overkill for this app. In my opinion, we could achieve the same things (like hiding the `div` etc.) with Vanilla JS - the Bassa Extension would be faster and won't require the user to download the JQuery with the extension (it happens automatically, but after all the JQuery would be packed with the extension)

**Comment by rohancl** [comment]
Nice Catch Lucas, I do agree the JQuery import is only being used for the hide() function for div(s), but in future we may use more of the functions present in JQuery file, So the better option would be to just leave this as it is for now. In future, When we're done building, <b>We may switch to Vanilla JS :wink: </b>
And as for importing whole JQUERY file along with the extension. It's a must since chrome doesn't allow you to import script in html lilke 
```<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">``` 
due to security reasons
